apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-score-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-score-service
  template:
    metadata:
      labels:
        app: credit-score-service
    spec:
      containers:
        - name: credit-score-service
          image: credit-score-service:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: credit-score-service
spec:
  selector:
    app: credit-score-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
